FROM node:20-alpine

ARG NODE_ENV
ARG MONGODB_URI
ARG KEYCLOAK_URL
ARG KEYCLOAK_REALM
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ENV NODE_ENV=production
ENV MONGODB_URI=$MONGODB_URI
ENV KEYCLOAK_URL=$KEYCLOAK_URL
ENV KEYCLOAK_REALM=$KEYCLOAK_REALM
ENV KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
ENV KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET

WORKDIR /app

COPY package.json /app/
COPY yarn.lock /app/
# COPY .env ./

RUN yarn 

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start:prod"]