FROM node:20-alpine

ARG NODE_ENV
ARG MONGODB_URI
ARG KEYCLOAK_URL
ARG KEYCLOAK_REALM
ARG KEYCLOAK_CLIENT_ID
ARG FRONTEND_URL

ENV NODE_ENV=production
ENV MONGODB_URI=$MONGODB_URI
ENV KEYCLOAK_URL=$KEYCLOAK_URL
ENV KEYCLOAK_REALM=$KEYCLOAK_REALM
ENV KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
ENV FRONTEND_URL=$FRONTEND_URL

WORKDIR /app

COPY package.json /app/
COPY yarn.lock /app/

RUN yarn 

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["node", "dist/main.js"]
